### ISSUE TITLE
How to remove strikethrough from completed to-do lists/checkbox

### ISSUE THREAD

**Issue by mtisec** [primary-theme/obsidian#161]
Hi Cecilia, I freaking love your theme! It is pure perfection! ... with one thing I'd like to change. I wish I could remove the strikethrough from checked boxes. I tried multiple things. Among them was the snippet from https://github.com/Dmytro-Shulha/obsidian-css-snippets/blob/master/Snippets/Check%20box.md
```css
/* Remove strikethrough from completed to-do lists/checkbox */  
.markdown-preview-view ul > li.task-list-item.is-checked {
    text-decoration: none;
    color: inherit;
}
```

It all doesn't work and I couldn't figure out yet, how the whole Obsidian CSS styling works. I have a bare minimum grasp of CSS, but that's all. I'd love to hear from you with an idea :)

PS: I think it would also be a perfect addition for Style Settings. I often create checklists that I want to export later for others and having my selections striked is really hard to read.

**Comment by mtisec** [comment]
I found the lines that disable strikethrough on hover of a checked box. It's line 2682-2685 in the current version of the theme.
```css
.markdown-source-view .HyperMD-task-line:is([data-task=x], [data-task=X]):hover,
.task-list-item.is-checked:hover {
  text-decoration: unset;
}
```

and these lines - that seem to be from the original Obsidian CSS - seem to be responsible for the strikethrough:
```css
.markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="x"], .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="X"] {
    text-decoration: line-through;
    color: var(--text-faint);
}
```

I'll try overwriting them with a snippet now and come back here :)

**Comment by mtisec** [comment]
Works like a charm 🤩 

Everything necessary was to add the following lines to a snippet and activate it:
```css
.markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="x"], .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="X"] {
    text-decoration: unset;
    color: var(--text-faint);
}
```
![2022-09-13 19_53_38-Theme - Primary Demo File - Obsidian Vault - Obsidian v0 15 9](https://user-images.githubusercontent.com/81265371/189976029-dd3cd753-c45b-4e6e-9cc9-1dafe1cfc65e.png)

I am not sure if `text-decoration: unset;` is the logically best choice, but that's what hovering did.
Trying now to add that to the Style Settings and creating a pull request ❤️
