### ISSUE TITLE
Default check marks still visible in alternate checkboxes

### ISSUE THREAD

**Issue by John-Miller12** [primary-theme/obsidian#170]
![Screenshot 2022-12-08 121403](https://user-images.githubusercontent.com/67792124/206533345-9ef567f2-7679-420b-94dd-4dba3933ca7e.png)

Hello, and thanks to Cecilia and any other contributors!!

**App version**: `v1.0.3`
**Theme version**: Up-to-date per obsidian

Ever since updating to `v1.0.3`, I am seeing small check marks on top of the custom icons, my favorite feature of this theme. I have attempted to locate the issue in the theme CSS, but I lack the skill needed in this language to ID the issue. In my .obsidian/Themes folder, I see only the folder "Primary" which contains `manifest.json` and `theme.css`. I do not have anything in my snippets folder.

Any support is appreciated!!

**Comment by slow47** [comment]
hi i know I'm 2 years late but this might help you 
add this to `.obsidian\snippets\` name it anything .css 

```css
/* Hide check marks */
input[type=checkbox]:checked::after {
  display: none !important;
}
/* Hide undesirable borders */
.HyperMD-list-line input[type="checkbox"]:checked {
  border: none !important;
}
/* Disable strike-through in markdown mode */
.markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="x"], .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task="X"] {
  text-decoration: unset;
  color: var(--text-faint);
}

/* Disable strike-through in preview mode */
ul > li.task-list-item[data-task="x"], ul > li.task-list-item[data-task="X"] {
  text-decoration: unset;
  color: var(--text-faint);
}
```
