### ISSUE TITLE
Side-bar items are moved on every ui update in Obsidian Version 1.3.4

### ISSUE THREAD

**Issue by edwardremo-chromedia** [primary-theme/obsidian#179]
![Screenshot 2023-05-25 at 11 26 42](https://github.com/ceciliamay/obsidianmd-theme-primary/assets/91073398/05685081-a89f-492e-9466-cdaddd03fba8)

**Comment by David-Carlson** [comment]
I think I'm having a similar issue: opening/closing folders causes the folder and items below to keep moving right, making it basically impossible to use the folder sidebar. 
![Screenshot from 2023-06-13 22-58-31](https://github.com/ceciliamay/obsidianmd-theme-primary/assets/2913852/e6f65d8a-5e4d-4d34-98da-d22e0eccf332)

**Comment by JustinThomason** [comment]
I'm also having this exact issue with the file sidebar. It is VERY frustrating as I love Primary and use it as my daily driver.

**Comment by patrickchan911** [comment]
I don't understand why change the CSS will cause this issue. Looks like some scripts are executed based on some theme parameters.

**Comment by Lordeblader** [comment]
I found out that removing the `transition` property from some classes fixes it. Here's a quick css snipet that should work:

```css
.nav-folder-title,
.nav-file-title {
  transition: none;
}

.tree-item-self {
  transition: none;
}

.tree-item-self .tree-item-icon {
  margin-left: -20px;
}

.tree-item-children:not(.graph-control-section .tree-item-children) {
  margin-left: 0;
}

.tree-item-children:not(.graph-control-section .tree-item-children) .tree-item {
  margin-left: 0;
}

```
