### ISSUE TITLE
Any plans for a port to VS Code?

### ISSUE THREAD

**Issue by hbarudin** [primary-theme/obsidian#87]
I just discovered this theme and just 💖  love it. Thank you @ceciliamay ! 

Are there any plans to take this theme to other apps (like how [Dracula](https://draculatheme.com/) has all kinds of apps you can use with it)? I'd loooove to have my VS Code be all Primary-awesome.

Are you open to other contributors? I'd love to lend a hand if I can!

**Comment by ceciliamay** [comment]
Hello there @hbarudin !! Thank you so so much for the kind words 🫂💖

Very timely of you, I'm actually working on the VSCode and a Logseq port right now! I'm currently trying to fine tune some colors so that I can make a contributor's guide and open up public contributions by trying to work out Primary for these two apps first. I'll keep this issue up and update you when it comes out!

Quick q, what languages do you use?

**Comment by chrisgrieser** [comment]
just to piggyback: a Sublime Color Scheme + base16 Terminal theme would be much appreciated, too :)

**Comment by spcbfr** [comment]
Here's an alacritty port I made, it looks kinda bad but it could be a starter if you haven't started working on it yet!
Code:
```yaml
  primary_dark: &primary_dark
    primary:
      background: '#231E1A'
      foreground: '#E5CFB3'
    normal:
      black:  '#1B1613'
      red:    '#F54E42'
      green:  '#38B27D'
      yellow: '#EBC400'
      blue:   '#4DADD5'
      magenta: '#9F78DD'
      cyan:    '#3399C1'
      white:   '#F6E7D5'
    bright:
      black:  '#2C2621'
      yellow: '#F8D668'
      red:    '#FF675C'
      green:  '#38D687'
      magenta: '#A993E6'
      white:   '#F6E7D5'
```
Preview:
![image](https://user-images.githubusercontent.com/77839865/161364876-f3c628aa-22b6-4b40-97b3-7bf9c553fdb0.png)
